### ISSUE TITLE
New data model and Fix issue flow (this needs redesign/sync with PF2050 data standards)

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#104]
![image](https://user-images.githubusercontent.com/80499565/153665047-04341d0e-7104-410e-a6c3-62dfc269a146.png)

[Inspection Form v2.docx](https://github.com/TrapScan/TrapScan/files/8051638/Inspection.Form.v2.docx)

https://miro.com/app/board/o9J_l_IphxI=/?invite_link_id=703121220484

- [ ] Include "TrapScan" in notes (and append " "&{{notes written in inspection}}) when uploading to Trap.NZ, so that pcords can filter their records by traditional- vs trapscan-uploaded

- [ ] Kurtis test this in prod when done

**Comment by KurtisPapple** [comment]
1) change all fields to future state (this ticket)
2) fix upload logic (96)
3) retro upload missing inspections (manual step)
4) 🍻

**Comment by KurtisPapple** [comment]
![image](https://user-images.githubusercontent.com/80499565/157401723-4e69cf2f-0c97-435d-8c6d-762ad6571313.png)

**Comment by DylanHobbs** [comment]
Devnotes

- [ ] Ensure mandatory note steps go straight to notes to prompt adding notes
- [ ] Ensure strikes is set correctly
- [ ] QR code broken should not upload to trapNZ

**Comment by DylanHobbs** [comment]
@KurtisPapple Need icons for these buttons too
![image](https://user-images.githubusercontent.com/8566772/157401877-0b664a82-3684-4942-8e3b-574f4f5e135d.png)
