### ISSUE TITLE
Update App logo

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#109]
logo with updated colour
https://drive.google.com/file/d/1WA8Q0ultsbxUbws9-qZSBWM7aFQSd5d-/view?usp=sharing
Google Docs
TrapScan logo v2 trans.svg
Image
might fix app logo as well, because transparent so can set background colour separate
#0AB587

**Comment by DylanHobbs** [comment]
@KurtisPapple think we'll need this for the app logo too with the writing, current one is below.

![image](https://user-images.githubusercontent.com/8566772/153212750-1b55276f-2272-490f-a48d-f0900787668a.png)
