### ISSUE TITLE
App to create QR records for printing

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#14]
So long as there is a way for me to generate QR records, with IDs based on words I feed in as discussed, and maybe a way to export a list of all QRs and if they have been assigned or not

Maori words to be used with letters/numbers to create IDs:
(full sheet here https://docs.google.com/spreadsheets/d/1UXc6SAOCHwnkGeJa0dZWmn-GuhllmiCqgwqsHMXnY5U/edit?usp=sharing)
awa
hui
iti
kai
moa
nui
wai
roa
one
pae
tai
ihu
tui
kea
haka
hapu
kiwi
koha
mahi
mana
motu
puku
waka
tapu
papa
poto
puke
niho
poho
raho
toto
turi
hihi
huia
kaka
tara
ruru
weka
whio
tane
rimu
rata
puha
miro
tawa
tutu
aroha
hangi
kauri
moana
arero
kauae
ringa
upoko
totoa
kuaka
torea
poaka
tieke
mauri
aruhe
nikau
matai
wheki
ponga
hinau
raupo
manawa
kakapo
kereru
kotuku
takapu
matata
matuku
karoro
piopio
kokako
koreke
kawau
kotare
parera
pukeko
hokioi
hoiho
korora
takahe
totara
manuka
kanuka
kowhai
tawhai
mamaku
katote
titoki

**Comment by DylanHobbs** [comment]
Implementation: Simple local app for Kurtis to run.
Takes a number and generates that many unmapped QR codes,
Pops them into Firebase
