### ISSUE TITLE
Informer/Anon inspection form

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#35]
For informers (people who won't sign up or clear traps, but will scan them to let people know something has been caught), create a simplified inspection form. This will only show if a user is not logged in.

Use Case:

1. New user sees the trap caught something
2. They scan QR
3. They see **3. Species Caught** and select what was caught
4. New Screen: "Thanks for letting us know. If you want to get full access to the TrapScan app please sign up (link to sign up page). or Log in (link to log in page)"

**Comment by DylanHobbs** [comment]
WIP PR is here #44 

Currently have no backend interaction.
@KurtisPapple what do we want to do with these?

**Comment by DylanHobbs** [comment]
- Create as real inspection
- Send notifications
- Do not upload to TrapNZ

**Comment by DylanHobbs** [comment]
This is also pretty much good to go.
Needs a test on live.

- [ ] Create or retrieve a qr code from the database
- [ ] Navigate to https://trapscan.app/scan/<qr_code>
- [ ] Or scan a code with the same address
- [ ] Ensure the simple for displayed
- [ ] Submit an inspection
- [ ] Verify inspection is in the DB

**Comment by KurtisPapple** [comment]
@DylanHobbs I submitted an anon under test-44444
Haven't looked in DB though
