### ISSUE TITLE
QR Installation form

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#4]
This is required so that physical QR codes can be installed on traps, use case:

1. Physically attach the QR code to the trap
2. Scan the QR code, the app loads and if the user is an admin, _and_ the scanned QR’s *Trap NZ ID field is Null, then view this QR installation form instead of the inspection form. 
 If the QR has a Trap NZ ID, then on the inspection form, show a small link to edit the QR installation (in case the Trap NZ ID has been set incorrectly, so it can be fixed in the field)

*Trap NZ ID is the national database ID for the trap which we will have to have https://www.trap.nz/

AC

1. If an admin or project coordinator (TrapScan) scans a QR and the QR **does** **not** have a Trap NZ ID attached to it (or doesn't exist in our DB at all), then this form appears rather than the Inspection Flow
2.  If an admin or project coordinator (TrapScan) scans a QR and the QR **does** have a Trap NZ ID attached, then include a small link to edit the installation, at the beginning of the Inspection Flow
3. When installation form is submitted, it saves the trap into Firestore 
4. The data saved includes:
 - **QR ID** 
 - **Trap NZ ID** (the 'code' of the trap in the existing Trap NZ database)
 - **Installed by** (Trap NZ 'Installed by' value - this optional and only used to "tie break" duplicate Trap NZ IDs - because they allow you to do that...)
 -  **Project name** (Trap NZ project name)

**Comment by DylanHobbs** [comment]
It'd be pretty cool to grab the users current location and pop that into the trap at the time
