### ISSUE TITLE
Set up About page

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#54]
TrapScan is a mobile web application designed by conservation volunteers to help simplify the administrative parts of their work.

Our first mission is to improve data quality and coverage by making data capture and consumption easier and more intuative:
- "Capture" meaning the recording of volunteer activity and trapping results. 
- "Consumption" meaning the viewing of what's recorded in an easy and intelligent way, to allow for more data-driven decision-making. 

We want both experiences to be as user friendly as possible and accessible to everyone.

Our second mission is to assist project coordinators in managing their volunteer base. We want to remove some of the common pain points they face, and help them to get more done in less time. We believe that without these unsung heroes we wouldn't have a chance, so want to repay their efforts by catering directly to them.

TrapScan is in it's first release so if you find any bugs, have ideas or any feedback, we would love to hear from you.
(link to contact form)

**The significance of our wildlife and the problem of mammalian pests**

Aotearoa New Zealand was isolated for 80 million years and was the last place on earth that primates set foot. Flora and fauna evolved in a very curious and unique way with the absence of predatory mammals, and many of our species are only found here which makes them internationally significant.

The introduction of mammalian pests with the arrival of humans led to the extinction of over 65 of our most treasured species and to this day we are still losing the battle… 

> Every year an army of introduced predators devours the eggs and chicks of some 26 million native New Zealand birds, as well as countless insects, amphibians, reptiles and plants. We currently have more than 4000 natives on the threatened species list and many more vulnerable to predation – New Zealand’s catalogue of shame.
But in 2016, the nation decided enough was enough. Predator Free 2050 was born — an eviction order served on the three most voracious predators — rats, stoats and possums. It’s our most ambitious conservation effort ever and is to be enforced by hundreds of thousands of ordinary Kiwis.
In Fight for the Wild (https://www.rnz.co.nz/programmes/fight-for-the-wild) we walk with the kaitiaki, ecologists, inventors and community trappers desperately defending our taonga species. We follow the fortunes of kea, kiwi, kakariki and other native species and discover the fascinating initiatives underway as we come to their rescue. We examine the tough choices our nation needs to make as we navigate the challenges of protecting our wildlife. And among the hard decisions and desperate losses, we discover bold visions, hard won victories and hope.
Fight for the Wild (https://www.rnz.co.nz/programmes/fight-for-the-wild) is a call to action for all New Zealanders. It tells how each of us holds a piece of a jigsaw, and how, if we all play our part, we might just see a wilderness saved and our Wild returned.

**Comment by DylanHobbs** [comment]
There were some error in it, but it went live when I pulled to fix it
