### ISSUE TITLE
Re-map QR option for Pcords on inspection

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#58]
![image](https://user-images.githubusercontent.com/80499565/136648385-1374b15b-7baf-40ba-a83a-78dd2d6e767d.png)

Ability to scan a QR and change what Trap NZ trap it is mapped to

**Comment by DylanHobbs** [comment]
After remap, kick pcord back to home
Refresh data to pull in updates

**Comment by KurtisPapple** [comment]
This is needed - they made mistakes installing today. This is in review but I can't see the button in inspection form?
