### ISSUE TITLE
Contact form (for feedback, bugs, QR or Trap- specific issues etc.)

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#60]
Contact form

They choose one of three bold header texts below as an option to branch form. Then get shown the questions of that option:

# Bugs or issues with the app

 What is the issue related to?
- Scan QR
- Nearby Traps
- Data
- About
- Settings
- Usability or accessibility

Explain the issue 
_[multi line text input]_

# QR code or Trap issues

What is the QR ID?
_[single line text input]_

What is the Trap.NZ trap ID? 
_[single line text input]_

Explain the issue
_[multi line text input]_

# Feedback, suggestions, or contact us

Feedback or suggestions
_[multi line text input]_

General questions or comments
_[multi line text input]_

Rate TrapScan.app 
_[10 Stars or 10-point sliding scale]_

**Comment by DylanHobbs** [comment]
Devnote: Body is null, check data coming in
