### ISSUE TITLE
Style new QR scanner

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#72]
1) Yellow banner with white text saying "scanner paused" change to the red we have in the theme

3) "Request Camera Permission" change into a button the same style as Nearby Traps "tap to start scanning" (but without the target icon)

4) "Request Camera Permission" change the name to "Allow Camera Permissions"

5) "Select Camera" change to same style button and remove the count in brackets

6) hide the text that shows what camera you currently have selected (cos it's obvious you can see it lol)

7) "Stop scanning" change to same style button 

![Screenshot_20211027-081409.png](https://user-images.githubusercontent.com/80499565/138947059-9c4bf441-28d7-48e2-82ea-15f755400843.png)
![Screenshot_20211027-080037.png](https://user-images.githubusercontent.com/80499565/138943974-fc92748b-06e9-43d1-876b-3ff64600784c.png)

**Comment by DylanHobbs** [comment]
Devnote: On submit bring back to tab the user was last one
