### ISSUE TITLE
"word" updates in Step Form

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#74]
### First screen
Add ' to Somethings so it says `Something's wrong`:
![image](https://user-images.githubusercontent.com/80499565/139626873-a0d8a15b-85a2-48f1-b338-ce1cfb826d68.png)

_"Species Caught" screen --------------------------------------------_
### Selecting species add comma:
change from:
"${option} "
to:
`${option}, ` (has a space at the end)

_"Empty" screen changes --------------------------------------------_
### Bait was old:
change from:
"it was still set and the bait was bad, "
to: 
`it was still set and the bait was bad, ` (has a space at the end)

### Bait was taken:
change from:
"it was still set and the bait was missing, "
to: 
`it was still set and the bait was taken, ` (has a space at the end)

### Trap was sprung:
change from 
"it was triggered though, " 
to 
`it was sprung, ` (has a space at the end)

_"Bait" screen --------------------------------------------_
### I'm just letting you know
change from: 
"I didn't rebait it" 
to 
`and I'm just letting you know.`

### Previous bait still good:
change from: 
"and the bait was still good." 
to 
`and the bait was good so I didn't rebait it.`

### Previous bait was still good (bad/taken)
When selected should remove "Bait was bad"/"Bait was taken" words

Given "Bait was Bad"/"Bait was taken" was selected on the _Empty_" screen,
When I select "Previous bait still good" on the _Bait_ screen,
Then the words appended by clicking "Bait was Bad"/"Bait was taken" are removed
Whereas currently you get some illogical sentences:
![image](https://user-images.githubusercontent.com/80499565/139568790-611ab356-79b9-465a-ad24-e8a47b9c15be.png)

### Previous bait was still good (sprung)
When selected should append different words if "Trap was sprung" was chosen before it

Given "Trap was sprung" was selected on the _Empty_" screen,
When I select "Previous bait still good" on the _Bait_ screen,
Then the words appended by clicking "Previous bait still good" should mention the fact that you did reset the trap, but just didn't add new bait to it
Whereas currently the wording isn't very clear as to what the volunteer did:
![image](https://user-images.githubusercontent.com/80499565/139568845-247e6e55-ef77-4fcb-a672-82b17aff6e95.png)

**Comment by DylanHobbs** [comment]
@KurtisPapple I'd just like to say this is probably the most well written issue I've ever gotten
