### ISSUE TITLE
Landing page improvements (UX and branding)

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#75]
Update to be like:

![Welcome page.jpg](https://user-images.githubusercontent.com/80499565/139601710-5ba9dbb3-a549-490d-8889-582451aeb97d.jpg)

**Comment by DylanHobbs** [comment]
@KurtisPapple Is this the landing page for the anon scan or the main landing page for the app?

**Comment by KurtisPapple** [comment]
@DylanHobbs  it's anon SCAN only, not anon navigates to TrapScan.app (cos they couldn't submit inspection as don't have QR ID collected)
