### ISSUE TITLE
Investigate this error (screenshot of log in card)

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#78]
I was taking screenshots to explain how Nearby Traps and mapping QRs worked there, noticed that after a few minutes the console started filling up with errors:

![image](https://user-images.githubusercontent.com/80499565/139625892-b2a447ca-ef04-4a1d-b405-a37165547458.png)

![image](https://user-images.githubusercontent.com/80499565/139625933-2190db4e-e298-4026-a676-fa68608fbea5.png)

**Comment by DylanHobbs** [comment]
Yeah this is a rate limit that's imposed by default. I'm going to remove all limits for this route
