### ISSUE TITLE
"Alert Me" - email notifications when something is caught in a particular project

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#8]
This is a specific requirement from the local council who has seed funded this project. They are trying to eradicate all rats in a particular area https://www.pfw.org.nz/miramar/

They need biosecurity alerts set up - they are down to only a handful or Rats and need to be alerted if one is caught, so they can scan the perimeter for more

------

If project coordinator, option to select to receive notifications when a catch is reported for your project

This is to be set up specifically for Miramar peninsula to begin with

Email to be sent to email address of the project coordinator, with details of the inspection:
- Species caught
- Trap NZ ID (if blank then "The QR for this inspection hasn't been mapped to a Trap NZ ID - please have a Project Coordinator or Administrator "install" the QR by scanning it"
- QR ID 
- Time and date of the inspection
- Public name of the user who made the inspection

**Comment by DylanHobbs** [comment]
@KurtisPapple This is pretty much good to go.

Tested it with one project coordinator and a user submitting an inspection.
The filters work too.
