### ISSUE TITLE
When anon scan, go to register but then hit back. Blue circle of death

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#84]
![image](https://user-images.githubusercontent.com/80499565/140270136-04fc3b19-262f-4266-ae77-a7c1cd389836.png)

**Comment by DylanHobbs** [comment]
@KurtisPapple I can't seem to reproduce this :/

**Comment by KurtisPapple** [comment]
All good, isn't a biggie just thought I'd log it as a "fix it one day if bored and everything else is done"

**Comment by DylanHobbs** [comment]
Is there any other steps to make it happen?
I can't really fix it if I can't make it happen :/

**Comment by KurtisPapple** [comment]
We can just close the issue and if it pops up again deal with it then
