### ISSUE TITLE
Conditional rules for uploading to Trap.NZ

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#9]
EDIT:

Only upload inspections to Trap.NZ with the following conditions:

**Species Caught** != None [it caught something] AND
(**Rebaited** != No [they rebaited it] OR **Status** = Still set, bait OK)

------
Contract item:

 **"Data accuracy and integrity equal to that, or higher than Trap.NZ app"**

This is a requirement from primary stakeholders: May 26, 2021 

“the no duplicates relates to the validity and trustworthiness of the data coming in. I do think it is one of the fundamental building blocks that need to be sorted out fairly soon in the journey as it would affect the trust and the feasibility of it being used as a trapping assistant tool.

 

Data Accuracy and Integrity

Data uploaded to the Trap NZ database through TrapScan App is accurate, valid and overall reduces post upload editing for group co-ordinators.

We want the data to be accurate and valid (10 duplicated of one catch becomes invalid info, invalid perhaps not the right word), which means eliminating duplicates but we also want to cut down on post data upload processing for group co-ordinators, thus less fixing data through incorrect uploads.“

My reply:

I agree 100% with what you are saying and appreciate the words you made for us below (I love a good “why”!).

 

The concern I had was that currently there is no duplication filtering to Trap NZ at all right? For example I can check a trap, see a rat in it, don’t rebait it cos I’m a wimp, and using the Trap NZ app say “hey somethings in there and it needs rebaiting”, walk off, and the next person can do the same.

That is also the desired behaviour correct? I.e. we want people recording all activity so that there is a full record of activity in Trap NZ? (I recall there being a desire to get a read on total volunteer effort/hours? Which is why we want to record everything)

 

So I am running on two assumptions here that:

currently there is no filtering, and

we want all activity captured.

 

To get clear on what we are talking about with all activity, here’s a grid sowing the main 4 outcomes of a trap-checking activity:

- Empty, needs rebaiting
- Empty, rebaited
- Catch, needs rebaiting
- Catch, rebaited

 
In theory 2 people could submit the same “this trap caught something, but I didn’t rebait it” in the same day, and a third person with gumption could submit a “this trap caught something and I rebaited it”, resulting in 3 catch records against that trap for only a single kill, and that is the desired/ideal behaviour using Trap NZ App as of now?

 

That’s my current understanding anyway, which is where my concerns came about (do we really want to remove duplicated is that’s how we want it in those scenarios?). I have a solution though:

 

In TrapScan’s “intermediary” database we can and will capture all data (possibly including a “time spent” value, all for querying later).

We can then run a filter over if before uploading to Trap NZ (maybe nightly), saying “if any record in the same 24hr period has the same Trap ID, Species caught, and bait type values, then only submit one of them to Trap NZ”. (these three values cover all 4 scenarios above)

 

Does that sound right/good?

**Comment by DylanHobbs** [comment]
This is handled mostly by the backend, I believe we want the user to see there was nothing inherently "wrong" with their inspection, so it should appear as a success to them.

Current duplicate check looks like this, but it will need refining. Essentially just checks if there has been an inspection on this trap in the last hour

````php
$oneHourAgo = Carbon::now()->subHour();
$duplicate = Inspection::where('trap_id', $trap->id)
    ->where('created_at', '>=', $oneHourAgo)->first();
if (Inspection::where('trap_id', $trap->id)
    ->where('created_at', '>=', $oneHourAgo)->exists()) {
    return response()->json([
        'message' => 'Inspection was added < 1 hour ago, duplicate has been ignored',
        'data' => $duplicate->toArray()
    ], 200);
} else {
  // Save the inspections
}
````

**Comment by KurtisPapple** [comment]
Looks great thanks Dylan! I do think we need to firm up the business rules though; something like this is more necessary than just the previous hour:

 “if any record in the same 24hr period has the same Trap ID, Species caught, and bait type values, then only submit one of them to Trap NZ”.

Because I could scan a trap and say I didn't rebaits it, then 30 min later someone else scans it and they rebait it. What would happen then? Would the trap be baited but have thrown away the inspection that details what bait was used?

Or (and this has happened before) you perform and inspection and rebait a trap, then as you are walking away the trap goes off and you catch a mouse. Both inspections happened within a few min of each other, and both a completely valid.

**Comment by DylanHobbs** [comment]
EDIT:

Only upload inspections to Trap.NZ with the following conditions:

Species Caught != None [it caught something] AND
(Rebaited != No [they rebaited it] OR Status = Still set, bait OK)

**Comment by DylanHobbs** [comment]
Duplicate check either 30 seconds or not at all
