### ISSUE TITLE
Reword "I'm just LYK" so makes sense when no catch

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan#97]
![Screenshot_20220106-095646.png](https://user-images.githubusercontent.com/80499565/148288419-9e3ca782-38f4-4a4a-8ab1-d584e0cb1cd4.png)

Currently you see this even if you selected that the trap was empty (hasn't caught anything). Need to reword it into a "catch-all":

**I'm just letting you know** the trap caught something and/or needs rebaiting

**Comment by DylanHobbs** [comment]
@KurtisPapple should the "words" that get added on (for the end display summary) be changed to reflect this?

**Comment by KurtisPapple** [comment]
@DylanHobbs I believe the "words" just say "and I'm just letting you know", which should still work with the "words" that come before it?

E.g. for this case we are trying to solve:

"It was still set and the bait was missing" "and I'm just letting you know"

**Comment by DylanHobbs** [comment]
This is good to go then so
